package com.stratizen.core.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single event in the Stratizen system.
 *
 * Stored in the `events` Room table.
 * Includes metadata such as title, description, timestamp, and grouping.
 */
@Entity(tableName = "events")
data class Event(
    /**
     * Unique ID for each event.
     *
     * Auto-generated by Room. Required for database operations like updates/deletes.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    /**
     * Title of the event (e.g. "Group Meeting", "Hackathon").
     */
    val title: String,

    /**
     * Detailed description of the event.
     */
    val description: String,

    /**
     * Timestamp in milliseconds.
     *
     * Used for sorting chronologically or scheduling (e.g., System.currentTimeMillis()).
     */
    val timestamp: Long,

    /**
     * Group or category the event belongs to (e.g. "Academics", "Tech", "General").
     * Defaults to "General".
     */
    val group: String = "General"
)
